---
all:
  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  children:
    vagrant:
      vars:
        ansible_host: "{{ (vms | selectattr('name', 'equalto', inventory_hostname) | map(attribute='ip') | first)[0] }}"
        ansible_user: vagrant
        ansible_ssh_private_key_file: "{{ playbook_dir }}/../.vagrant/machines/{{ inventory_hostname }}/{{ ansible_host_hypervisor }}/private_key"
      children:
        vms:

vms:
  children:
    linux:
    win:

linux:
  children:
    rocky:
      hosts:
        rocky9:

win:
  vars:
    ansible_connection: winrm
    ansible_password: vagrant
    ansible_winrm_server_cert_validation: ignore
    # ansible_shell_type: powershell
  hosts:
    win2022:
